// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.CheckpointEntidad", b =>
                {
                    b.Property<int>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckpointId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("HoraPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraReal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("MudanzaId")
                        .HasColumnType("int");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.HasKey("CheckpointId");

                    b.HasIndex("MudanzaId");

                    b.ToTable("tbl_checkpoint", (string)null);
                });

            modelBuilder.Entity("Entidades.ClienteEntidad", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("tbl_cliente", (string)null);
                });

            modelBuilder.Entity("Entidades.EmpleadoEntidad", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_empleado", (string)null);
                });

            modelBuilder.Entity("Entidades.FacturaEntidad", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Impuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(18m);

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MudanzaId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("MudanzaId")
                        .IsUnique();

                    b.ToTable("tbl_factura", (string)null);
                });

            modelBuilder.Entity("Entidades.IncidenciaEntidad", b =>
                {
                    b.Property<int>("IncidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenciaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MudanzaId")
                        .HasColumnType("int");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IncidenciaId");

                    b.HasIndex("MudanzaId");

                    b.ToTable("tbl_incidencia", (string)null);
                });

            modelBuilder.Entity("Entidades.InventarioEntidad", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MudanzaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("MudanzaId");

                    b.ToTable("tbl_inventario", (string)null);
                });

            modelBuilder.Entity("Entidades.MudanzaEntidad", b =>
                {
                    b.Property<int>("MudanzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MudanzaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("MudanzaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("tbl_mudanza", (string)null);
                });

            modelBuilder.Entity("Entidades.PagoEntidad", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("tbl_pago", (string)null);
                });

            modelBuilder.Entity("Entidades.RolEntidad", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tbl_rol", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Descripcion = "Acceso completo al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Descripcion = "Supervisión de operaciones y empleados",
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            RolId = 3,
                            Descripcion = "Operaciones básicas de mudanza",
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("Entidades.UsuarioEntidad", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Contrasena = "admin123",
                            Correo = "admin@movesolutions.com",
                            Estado = "Activo",
                            NombreUsuario = "admin",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("Entidades.VehiculoEntidad", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("tbl_vehiculo", (string)null);
                });

            modelBuilder.Entity("Entidades.CheckpointEntidad", b =>
                {
                    b.HasOne("Entidades.MudanzaEntidad", "Mudanza")
                        .WithMany("Checkpoints")
                        .HasForeignKey("MudanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mudanza");
                });

            modelBuilder.Entity("Entidades.EmpleadoEntidad", b =>
                {
                    b.HasOne("Entidades.UsuarioEntidad", "Usuario")
                        .WithMany("Empleados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entidades.FacturaEntidad", b =>
                {
                    b.HasOne("Entidades.MudanzaEntidad", "Mudanza")
                        .WithOne("Factura")
                        .HasForeignKey("Entidades.FacturaEntidad", "MudanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mudanza");
                });

            modelBuilder.Entity("Entidades.IncidenciaEntidad", b =>
                {
                    b.HasOne("Entidades.MudanzaEntidad", "Mudanza")
                        .WithMany("Incidencias")
                        .HasForeignKey("MudanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mudanza");
                });

            modelBuilder.Entity("Entidades.InventarioEntidad", b =>
                {
                    b.HasOne("Entidades.MudanzaEntidad", "Mudanza")
                        .WithMany("Inventario")
                        .HasForeignKey("MudanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mudanza");
                });

            modelBuilder.Entity("Entidades.MudanzaEntidad", b =>
                {
                    b.HasOne("Entidades.ClienteEntidad", "Cliente")
                        .WithMany("Mudanzas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades.EmpleadoEntidad", "Empleado")
                        .WithMany("Mudanzas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entidades.UsuarioEntidad", "Usuario")
                        .WithMany("Mudanzas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entidades.VehiculoEntidad", "Vehiculo")
                        .WithMany("Mudanzas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Entidades.PagoEntidad", b =>
                {
                    b.HasOne("Entidades.FacturaEntidad", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Entidades.UsuarioEntidad", b =>
                {
                    b.HasOne("Entidades.RolEntidad", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entidades.ClienteEntidad", b =>
                {
                    b.Navigation("Mudanzas");
                });

            modelBuilder.Entity("Entidades.EmpleadoEntidad", b =>
                {
                    b.Navigation("Mudanzas");
                });

            modelBuilder.Entity("Entidades.FacturaEntidad", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Entidades.MudanzaEntidad", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Factura");

                    b.Navigation("Incidencias");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Entidades.RolEntidad", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Entidades.UsuarioEntidad", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Mudanzas");
                });

            modelBuilder.Entity("Entidades.VehiculoEntidad", b =>
                {
                    b.Navigation("Mudanzas");
                });
#pragma warning restore 612, 618
        }
    }
}
